### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by Heroshrine** [Faenum/NFINITColonies#2]
I'm not the best at reading crash logs, but it looks like it crashed after 'deduplicating models'

Log:
https://pastebin.com/ReS74CnE

**Comment by Faenum** [comment]
thats odd, not seen that one before, did you try loading it again?

**Comment by Heroshrine** [comment]
I did try loading it again, and it worked, but every once in a while (pretty rare) it just crashes, and it always ends at the same place as in that log.

EDIT: So after another crash at the same place, the server IP was no longer built into the pack.

**Comment by Faenum** [comment]
thats very odd, which version are you using? all i can suggest is to try deleting the pack and reinstalling it. ive loaded it many times, and while its had a few crashes, loading it again always works.
